### ISSUE TITLE
Facilitate API communication logging

### ISSUE THREAD

**Issue by bhudgeons** [finagle/featherbed#12]
When implementing a new API client, it is very useful to have verbose logging of what you're sending and receiving (so you can debug & easily send logs to API vendors to report problems without resorting to some external tool). I'm happy to take a stab at adding it, but don't want to introduce a logging framework unless you agree with it. Do you prefer to add a logging framework (which one) and configure logging levels in the traditional way, or would it be better to have something like client.get(path).verboselog(true)?

**Comment by jeremyrsmith** [comment]
@bhudgeons I'm thinking maybe this can be handled at the finagle-http layer, using `Tracing`? If you have time to investigate that possibility it would be great.

**Comment by bhudgeons** [comment]
@jeremyrsmith will do.

**Comment by jeremyrsmith** [comment]
@bhudgeons I'm going to go ahead and close this, because I'm pretty confident that this should be handled with lower level finagle primitives. If we need to make some changes to support configuring `Tracing` and `Stats` then I'm open to a PR for that.
