### ISSUE TITLE
vargs in query string implementation causes errors

### ISSUE THREAD

**Issue by bhudgeons** [finagle/featherbed#26]
error is explained in #23.

**Comment by ilya-murzinov** [comment]
@bhudgeons can you please share the sample code? This one compiles fine:
```scala
client
      .get("foo/bar")
      .addQueryParams("param1" -> "value1", "param2" -> "value2", "param2" -> "value2")
      .addQueryParams("param2" -> "value2")
      .addQueryParams("param2" -> "value3")
      .accept("text/plain")
      .addQueryParams("param1" -> "value1", "param2" -> "value2", "param2" -> "value2")
```

**Comment by bhudgeons** [comment]
@ilya-murzinov check out https://github.com/bhudgeons/featherbed/commit/6d2465b37bbbe0598dfdb6d3ca17bf87f2dd443c

**Comment by bhudgeons** [comment]
@ilya-murzinov map makes more sense as a key->value parameter list anyway, and it avoids https://issues.scala-lang.org/browse/SI-7420

**Comment by jeremyrsmith** [comment]
@bhudgeons Why do you need to define that type alias?  It is unfortunate that such a strange problem occurs, but I don't think removing the varargs method is the solution.  We could have both a varargs method and a `List` method, if that would be helpful.  But I don't see the need for the type alias to begin with.

**Comment by bhudgeons** [comment]
@jeremyrsmith https://finagle.github.io/featherbed/doc/04-building-rest-clients.html :)    ... you're exactly right ... the way to fix it is with a couple of convenience methods that accept List instead of varargs. One sec.

**Comment by jeremyrsmith** [comment]
@bhudgeons Yikes, that documentation is what needs to change.  It's preferable now to use `.accept("application/json")`, since you don't have to specify it as a type argument anymore.

**Comment by jeremyrsmith** [comment]
@bhudgeons which obviates the need for the type alias

**Comment by bhudgeons** [comment]
In that case, (1) does the PR potentially get rid of other similar issues, and (2) are the convenience methods worth the code clutter. I'd bet most query parameter lists are built with maps, since that's the most natural key-value collection. I understand that we must support "param1=x&param1=y" query strings. With just the varargs, there's going to be a lot of ```mymap.toList: _*``` going on.

**Comment by jeremyrsmith** [comment]
I think this has been fixed by the changes to how params are specified; I'm going to close this but please reopen if you still have this problem @bhudgeons
