### ISSUE TITLE
Simple example fails

### ISSUE THREAD

**Issue by wulftone** [finagle/featherbed#34]
This is taken straight from the documentation and it appears that `map` is not a valid method on a request, which seems silly, but there it is!  Maybe it has to do with how I compiled the project (See https://github.com/finagle/featherbed/issues/33)?

``` scala
val client = featherbed.Client(new URL("http://localhost:8888/"))
// client: featherbed.Client = featherbed.Client@4a02fb3c

val req = client.get("")
// req: client.GetRequest[shapeless.:+:[String("*/*"),shapeless.CNil]] = GetRequest(http://localhost:8888/,List(),UTF-8)

val result = Await.result { req map { r => r.contentString } }
// <console>:15: error: value map is not a member of client.GetRequest[shapeless.:+:[String("*/*"),shapeless.CNil]]
//        val result = Await.result { req map { r => r.contentString } }
//                                        ^
```

**Comment by wulftone** [comment]
I see now I was working with a newer version than the published docs are.  The docs in the repo != docs on the web, and they do have a working example.

**Comment by ilya-murzinov** [comment]
@wulftone seems now everything is ok, can we close this?
