### ISSUE TITLE
Bump Finagle Version to 6.38.0

### ISSUE THREAD

**Issue by RayRacine** [finagle/featherbed#42]
There was a change in Twitter Common 6.34.0 that is causing a dynamic class load failure in Featherbed 0.2.1-SNAPSHOT at Finagle at 6.35.0.   I'm not sure how common this is or is simply highly specific to my dependency stack (extensive) and the ensuing evictions (hellish).

However, I have found Finagle 6.38.0 is a been stable least upper bound which compiles clean and has been solid for me so far with _light_ duty Featherbed usage.

Like to bump 0.2.1-SNAPSHOT up to Finagle 6.38.0

**Comment by jeremyrsmith** [comment]
This is done with #43 (we'll probably have to move to 6.39.0 soon though!)
