### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by Rydgel** [finagle/featherbed#49]
Do you think featherbed should support making a websockets client?
Or do you think this belongs to another project?

**Comment by ilya-murzinov** [comment]
It probably makes sense to have sub-project ```featherbed-websockets```

**Comment by jeremyrsmith** [comment]
@Rydgel @ilya-murzinov I think featherbed's goal is to focus pretty narrowly on REST; websockets seem like they're outside of that scope. That being said, if there's no client library for websockets, and it makes sense to share abstractions with featherbed, I'm not opposed to a featherbed-websockets module.
