### ISSUE TITLE
0.3.0: sbt requires tut for using featherbed

### ISSUE THREAD

**Issue by bhudgeons** [finagle/featherbed#64]
@jeremyrsmith is already aware of this, but just wanted to leave this here in case someone else had trouble using the new release. 

If you're using ```"io.github.finagle" % "featherbed_2.11" % "0.3.0"```, somehow tut has become a dependency.

Workaround: add ```"tpolecat Repo" at "http://dl.bintray.com/tpolecat/maven/"``` to your resolvers in build.sbt. You'll just be downloading some jars you don't actually need.

**Comment by jeremyrsmith** [comment]
Solved by #66
